In [16]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('occupancy.csv')
df

datetime  temperature  relative humidity   light      C02  \
0      2015-02-04 17:51:00       23.180            27.2720  426.00   721.25   
1      2015-02-04 17:51:59       23.150            27.2675  429.50   714.00   
2      2015-02-04 17:53:00       23.150            27.2450  426.00   713.50   
3      2015-02-04 17:54:00       23.150            27.2000  426.00   708.25   
4      2015-02-04 17:55:00       23.100            27.2000  426.00   704.50   
...                    ...          ...                ...     ...      ...   
20555  2015-02-18 09:15:00       20.815            27.7175  429.75  1505.25   
20556  2015-02-18 09:16:00       20.865            27.7450  423.50  1514.50   
20557  2015-02-18 09:16:59       20.890            27.7450  423.50  1521.50   
20558  2015-02-18 09:17:59       20.890            28.0225  418.75  1632.00   
20559  2015-02-18 09:19:00       21.000            28.1000  409.00  1864.00   

       humidity  occupancy  
0      0.004793          1  
1      0.004783          1  
2      0.004779          1  
3      0.004772          1  
4      0.004757          1  
...         ...        ...  
20555  0.004213          1  
20556  0.004230          1  
20557  0.004237          1  
20558  0.004279          1  
20559  0.004321          1  

[20560 rows x 7 columns]

In [18]:
features = ["temperature", "relative humidity", "light", "C02", "humidity"]
#classes = ['unoccupied', 'occupied']

In [19]:
x = df[features]
x

temperature  relative humidity   light      C02  humidity
0           23.180            27.2720  426.00   721.25  0.004793
1           23.150            27.2675  429.50   714.00  0.004783
2           23.150            27.2450  426.00   713.50  0.004779
3           23.150            27.2000  426.00   708.25  0.004772
4           23.100            27.2000  426.00   704.50  0.004757
...            ...                ...     ...      ...       ...
20555       20.815            27.7175  429.75  1505.25  0.004213
20556       20.865            27.7450  423.50  1514.50  0.004230
20557       20.890            27.7450  423.50  1521.50  0.004237
20558       20.890            28.0225  418.75  1632.00  0.004279
20559       21.000            28.1000  409.00  1864.00  0.004321

[20560 rows x 5 columns]

In [20]:
#this is pandas series
y = df.occupancy
y

0        1
1        1
2        1
3        1
4        1
        ..
20555    1
20556    1
20557    1
20558    1
20559    1
Name: occupancy, Length: 20560, dtype: int64

In [21]:
#this is a list
koko= [['a',3,5.5],
      ['b',6,8.5]] 
type(koko)

list

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)
x

array([[2.31800000e+01, 2.72720000e+01, 4.26000000e+02, 7.21250000e+02,
        4.79298818e-03],
       [2.31500000e+01, 2.72675000e+01, 4.29500000e+02, 7.14000000e+02,
        4.78344095e-03],
       [2.31500000e+01, 2.72450000e+01, 4.26000000e+02, 7.13500000e+02,
        4.77946352e-03],
       ...,
       [2.08900000e+01, 2.77450000e+01, 4.23500000e+02, 1.52150000e+03,
        4.23681810e-03],
       [2.08900000e+01, 2.80225000e+01, 4.18750000e+02, 1.63200000e+03,
        4.27948547e-03],
       [2.10000000e+01, 2.81000000e+01, 4.09000000e+02, 1.86400000e+03,
        4.32073200e-03]])

In [23]:
type(x)

numpy.ndarray

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

  (0, 384)	1.0
  (0, 485)	27.272
  (0, 486)	426.0
  (0, 487)	721.25
  (0, 488)	0.0047929881765052
  (1, 381)	1.0
  (1, 485)	27.2675
  (1, 486)	429.5
  (1, 487)	714.0
  (1, 488)	0.0047834409493106
  (2, 381)	1.0
  (2, 485)	27.245
  (2, 486)	426.0
  (2, 487)	713.5
  (2, 488)	0.0047794635244219
  (3, 381)	1.0
  (3, 485)	27.2
  (3, 486)	426.0
  (3, 487)	708.25
  (3, 488)	0.0047715088260817
  (4, 376)	1.0
  (4, 485)	27.2
  (4, 486)	426.0
  (4, 487)	704.5
  (4, 488)	0.0047569929333151
  :	:
  (20555, 140)	1.0
  (20555, 485)	27.7175
  (20555, 486)	429.75
  (20555, 487)	1505.25
  (20555, 488)	0.0042129681932869
  (20556, 146)	1.0
  (20556, 485)	27.745
  (20556, 486)	423.5
  (20556, 487)	1514.5
  (20556, 488)	0.0042302619316022
  (20557, 149)	1.0
  (20557, 485)	27.745
  (20557, 486)	423.5
  (20557, 487)	1521.5
  (20557, 488)	0.0042368181014067
  (20558, 149)	1.0
  (20558, 485)	28.0225
  (20558, 486)	418.75
  (20558, 487)	1632.0
  (20558, 488)	0.0042794854718673
  (20559, 160)	1.0
  (20559, 485)

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [27]:
print(y)

[1 1 1 ... 1 1 1]


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= .2 , random_state= 1)

TypeError: Singleton array array(<20560x489 sparse matrix of type '<class 'numpy.float64'>'
	with 90028 stored elements in Compressed Sparse Row format>, dtype=object) cannot be considered a valid collection.

In [ ]:
x_train

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.72227857e+01, 4.19000000e+02, 7.01666667e+02,
        4.75699300e-03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72000000e+01, 4.26000000e+02, 7.04500000e+02,
        4.75699300e-03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72720000e+01, 4.26000000e+02, 7.21250000e+02,
        4.79298800e-03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72000000e+01, 4.26000000e+02, 7.08250000e+02,
        4.77150900e-03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72675000e+01, 4.29500000e+02, 7.14000000e+02,
        4.78344100e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.72227857e+01, 4.19000000e+02, 6.99000000e+02,
        4.7

In [ ]:
x_test

array([[0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 2.724500e+01, 4.260000e+02, 7.135000e+02,
        4.779464e-03],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 2.717500e+01, 4.190000e+02, 6.880000e+02,
        4.745351e-03]])

In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
y_test

array([0, 0], dtype=int64)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[ 0.          0.          0.          1.73205081 -0.37796447 -0.11772956
  -0.96490128 -0.35207933 -0.71075395]
 [ 0.          0.          1.         -0.57735027 -0.37796447 -0.95696372
   0.75047877 -0.04115213 -0.71075395]
 [ 1.          0.          0.         -0.57735027 -0.37796447  1.694911
   0.75047877  1.79697634  1.9486973 ]
 [ 0.          0.          1.         -0.57735027 -0.37796447 -0.95696372
   0.75047877  0.37036917  0.36174485]
 [ 1.          0.          0.         -0.57735027 -0.37796447  1.52916883
   1.6081688   1.0013685   1.24332763]
 [ 0.          0.          0.          1.73205081 -0.37796447 -0.11772956
  -0.96490128 -0.6447167  -0.71075395]
 [ 0.          0.          0.         -0.57735027  2.64575131 -0.95696372
  -0.96490128 -1.70552717 -0.71075395]
 [ 0.          1.          0.         -0.57735027 -0.37796447 -0.11772956
  -0.96490128 -0.42523868 -0.71075395]]


In [ ]:
print(x_test)

[[ 0.          1.          0.         -0.57735027 -0.37796447  0.70045798
   0.75047877  0.94649899  0.94949133]
 [ 0.          0.          0.         -0.57735027  2.64575131 -1.87775355
  -0.96490128 -1.85184585 -1.57091041]]
