In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('occupancy_missing.csv')
df

datetime  temperature  relative humidity  light         C02  \
0  2015-02-04 17:51         22.0            27.2720  426.0  721.250000   
1  2015-02-04 17:51         22.0            27.2675  429.5  714.000000   
2  2015-02-04 17:53         23.0            27.2450  426.0  713.500000   
3  2015-02-04 17:54          NaN            27.2000  426.0  708.250000   
4  2015-02-04 17:55          NaN            27.2000  426.0  704.500000   
5  2015-02-04 17:55         23.0                NaN  419.0  701.000000   
6  2015-02-04 17:57         24.0                NaN  419.0  701.666667   
7  2015-02-04 17:57         24.0                NaN  419.0  699.000000   
8  2015-02-04 17:58         25.0            27.2000  419.0  689.333333   
9  2015-02-04 18:00         25.0            27.1750  419.0  688.000000   

   humidity  occupancy  
0  0.004793          1  
1  0.004783          1  
2  0.004779          1  
3  0.004772          1  
4  0.004757          1  
5  0.004757          1  
6  0.004757          1  
7  0.004757          1  
8  0.004757          1  
9  0.004745          1

In [3]:
features = ["temperature", "relative humidity", "light", "C02", "humidity"]
#classes = ['unoccupied', 'occupied']

In [4]:
x = df[features]
x

temperature  relative humidity  light         C02  humidity
0         22.0            27.2720  426.0  721.250000  0.004793
1         22.0            27.2675  429.5  714.000000  0.004783
2         23.0            27.2450  426.0  713.500000  0.004779
3          NaN            27.2000  426.0  708.250000  0.004772
4          NaN            27.2000  426.0  704.500000  0.004757
5         23.0                NaN  419.0  701.000000  0.004757
6         24.0                NaN  419.0  701.666667  0.004757
7         24.0                NaN  419.0  699.000000  0.004757
8         25.0            27.2000  419.0  689.333333  0.004757
9         25.0            27.1750  419.0  688.000000  0.004745

In [5]:
#this is pandas series
y = df.occupancy
y

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: occupancy, dtype: int64

In [6]:
#this is a list
koko= [['a',3,5.5],
      ['b',6,8.5]] 
type(koko)

list

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)
x

array([[2.20000000e+01, 2.72720000e+01, 4.26000000e+02, 7.21250000e+02,
        4.79298800e-03],
       [2.20000000e+01, 2.72675000e+01, 4.29500000e+02, 7.14000000e+02,
        4.78344100e-03],
       [2.30000000e+01, 2.72450000e+01, 4.26000000e+02, 7.13500000e+02,
        4.77946400e-03],
       [2.35000000e+01, 2.72000000e+01, 4.26000000e+02, 7.08250000e+02,
        4.77150900e-03],
       [2.35000000e+01, 2.72000000e+01, 4.26000000e+02, 7.04500000e+02,
        4.75699300e-03],
       [2.30000000e+01, 2.72227857e+01, 4.19000000e+02, 7.01000000e+02,
        4.75699300e-03],
       [2.40000000e+01, 2.72227857e+01, 4.19000000e+02, 7.01666667e+02,
        4.75699300e-03],
       [2.40000000e+01, 2.72227857e+01, 4.19000000e+02, 6.99000000e+02,
        4.75699300e-03],
       [2.50000000e+01, 2.72000000e+01, 4.19000000e+02, 6.89333333e+02,
        4.75699300e-03],
       [2.50000000e+01, 2.71750000e+01, 4.19000000e+02, 6.88000000e+02,
        4.74535100e-03]])

In [8]:
type(x)

numpy.ndarray

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72720000e+01 4.26000000e+02 7.21250000e+02
  4.79298800e-03]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72675000e+01 4.29500000e+02 7.14000000e+02
  4.78344100e-03]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72450000e+01 4.26000000e+02 7.13500000e+02
  4.77946400e-03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72000000e+01 4.26000000e+02 7.08250000e+02
  4.77150900e-03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72000000e+01 4.26000000e+02 7.04500000e+02
  4.75699300e-03]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.72227857e+01 4.19000000e+02 7.01000000e+02
  4.75699300e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 2.72227857e+01 4.19000000e+02 7.01666667e+02
  4.75699300e-03]
 [0.00

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= .2 , random_state= 1)

In [14]:
x_train

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.72227857e+01, 4.19000000e+02, 7.01666667e+02,
        4.75699300e-03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72000000e+01, 4.26000000e+02, 7.04500000e+02,
        4.75699300e-03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72720000e+01, 4.26000000e+02, 7.21250000e+02,
        4.79298800e-03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72000000e+01, 4.26000000e+02, 7.08250000e+02,
        4.77150900e-03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 2.72675000e+01, 4.29500000e+02, 7.14000000e+02,
        4.78344100e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.72227857e+01, 4.19000000e+02, 6.99000000e+02,
        4.7

In [15]:
x_test

array([[0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 2.724500e+01, 4.260000e+02, 7.135000e+02,
        4.779464e-03],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 2.717500e+01, 4.190000e+02, 6.880000e+02,
        4.745351e-03]])

In [16]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [17]:
y_test

array([0, 0], dtype=int64)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [19]:
print(x_train)

[[ 0.          0.          0.          1.73205081 -0.37796447 -0.11772956
  -0.96490128 -0.35207933 -0.71075395]
 [ 0.          0.          1.         -0.57735027 -0.37796447 -0.95696372
   0.75047877 -0.04115213 -0.71075395]
 [ 1.          0.          0.         -0.57735027 -0.37796447  1.694911
   0.75047877  1.79697634  1.9486973 ]
 [ 0.          0.          1.         -0.57735027 -0.37796447 -0.95696372
   0.75047877  0.37036917  0.36174485]
 [ 1.          0.          0.         -0.57735027 -0.37796447  1.52916883
   1.6081688   1.0013685   1.24332763]
 [ 0.          0.          0.          1.73205081 -0.37796447 -0.11772956
  -0.96490128 -0.6447167  -0.71075395]
 [ 0.          0.          0.         -0.57735027  2.64575131 -0.95696372
  -0.96490128 -1.70552717 -0.71075395]
 [ 0.          1.          0.         -0.57735027 -0.37796447 -0.11772956
  -0.96490128 -0.42523868 -0.71075395]]


In [20]:
print(x_test)

[[ 0.          1.          0.         -0.57735027 -0.37796447  0.70045798
   0.75047877  0.94649899  0.94949133]
 [ 0.          0.          0.         -0.57735027  2.64575131 -1.87775355
  -0.96490128 -1.85184585 -1.57091041]]
